kmeans:
  k: 5
  maxIter: 20

  seed: 21

data:
  data: "data/en.openfoodfacts.org.products.csv"
  columns: "configs/columns.json"

spark:
  app_name: "clusteroff"
  deploy_mode: "local"
  driver_memory: "4g"
  executor_memory: "16g"
  executor_cores: 1
  driver_cores: 1

db:
  keyspace: "off"
  table: "food"

save_to: "models/clusteroff"